### ISSUE TITLE
Crash when teleporting with RFtools dimensions

### ISSUE THREAD

**Issue by CobaltRealm** [Zairus/IskalliumReactors#14]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b142.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  LoadingPlugin (noRecipeBookv1.0.0_formc1.12.2.jar)
  FMLPlugin (elulib-0.1.11.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/2/18 12:10 PM
Description: Exception in server tick loop

java.lang.RuntimeException: class zairus.iskalliumreactors.tileentity.TileEntityIRPowerTap is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:78)
	at net.minecraft.tileentity.TileEntity.func_189517_E_(TileEntity.java:205)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187278_c(PlayerChunkMapEntry.java:175)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187276_a(PlayerChunkMapEntry.java:74)
	at net.minecraft.server.management.PlayerChunkMap.func_72683_a(PlayerChunkMap.java:356)
	at net.minecraft.server.management.PlayerList.func_72375_a(PlayerList.java:289)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:618)
	at mcjty.lib.varia.TeleportationTools.teleportToDimension(TeleportationTools.java:62)
	at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:144)
	at mcjty.rftools.ForgeEventHandlers.performDelayedTeleports(ForgeEventHandlers.java:69)
	at mcjty.rftools.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:94)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_962_ForgeEventHandlers_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1690803936 bytes (1612 MB) / 3963092992 bytes (3779 MB) up to 5674893312 bytes (5412 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6088m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2601 Optifine OptiFine_1.12.2_HD_U_C8 229 mods loaded, 229 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by WinterGrave** [comment]
Has been fixed by registering tile entities
